apiVersion: v1
kind: Service
metadata:
  name: llm-operator-controller-manager-metrics
  namespace: llm
spec:
  selector:
    app.kubernetes.io/name: llm-operator
  ports:
  - name: metrics
    port: 8081
    targetPort: metrics
  - name: healthz
    port: 8082
    targetPort: healthz