apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: llm-operator-controller-manager-pdb
  namespace: llm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llm-operator