---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llm.cogito.dev
  resources:
  - llmactivemodels
  - llmbackends
  - llmmodeloverlays
  - llmmodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llm.cogito.dev
  resources:
  - llmactivemodels/status
  - llmbackends/status
  - llmmodeloverlays/status
  - llmmodels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - llm.cogito.dev
  resources:
  - llmbackends/finalizers
  - llmmodels/finalizers
  verbs:
  - update
