{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "llm-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.metrics.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "llm-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | quote }}
{{- end }}
