apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- llm.cogito.dev_llmmodels.yaml
- llm.cogito.dev_llmmodeloverlays.yaml
- llm.cogito.dev_llmactivemodels.yaml
- llm.cogito.dev_llmbackends.yaml