//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package cogitodevv1alpha1

import (
	"encoding/json"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactSpec) DeepCopyInto(out *ArtifactSpec) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactSpec.
func (in *ArtifactSpec) DeepCopy() *ArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheState) DeepCopyInto(out *CacheState) {
	*out = *in
	if in.LastHydrated != nil {
		in, out := &in.LastHydrated, &out.LastHydrated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheState.
func (in *CacheState) DeepCopy() *CacheState {
	if in == nil {
		return nil
	}
	out := new(CacheState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUResourceRequirements) DeepCopyInto(out *GPUResourceRequirements) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUResourceRequirements.
func (in *GPUResourceRequirements) DeepCopy() *GPUResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(GPUResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMActiveModel) DeepCopyInto(out *LLMActiveModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMActiveModel.
func (in *LLMActiveModel) DeepCopy() *LLMActiveModel {
	if in == nil {
		return nil
	}
	out := new(LLMActiveModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMActiveModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMActiveModelList) DeepCopyInto(out *LLMActiveModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LLMActiveModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMActiveModelList.
func (in *LLMActiveModelList) DeepCopy() *LLMActiveModelList {
	if in == nil {
		return nil
	}
	out := new(LLMActiveModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMActiveModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMActiveModelSpec) DeepCopyInto(out *LLMActiveModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMActiveModelSpec.
func (in *LLMActiveModelSpec) DeepCopy() *LLMActiveModelSpec {
	if in == nil {
		return nil
	}
	out := new(LLMActiveModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMActiveModelStatus) DeepCopyInto(out *LLMActiveModelStatus) {
	*out = *in
	if in.TransitionStarted != nil {
		in, out := &in.TransitionStarted, &out.TransitionStarted
		*out = (*in).DeepCopy()
	}
	if in.TransitionDuration != nil {
		in, out := &in.TransitionDuration, &out.TransitionDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMActiveModelStatus.
func (in *LLMActiveModelStatus) DeepCopy() *LLMActiveModelStatus {
	if in == nil {
		return nil
	}
	out := new(LLMActiveModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBackend) DeepCopyInto(out *LLMBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackend.
func (in *LLMBackend) DeepCopy() *LLMBackend {
	if in == nil {
		return nil
	}
	out := new(LLMBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBackendList) DeepCopyInto(out *LLMBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LLMBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendList.
func (in *LLMBackendList) DeepCopy() *LLMBackendList {
	if in == nil {
		return nil
	}
	out := new(LLMBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBackendSpec) DeepCopyInto(out *LLMBackendSpec) {
	*out = *in
	out.DeploymentRef = in.DeploymentRef
	out.ServiceRef = in.ServiceRef
	if in.GPUResources != nil {
		in, out := &in.GPUResources, &out.GPUResources
		*out = new(GPUResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendSpec.
func (in *LLMBackendSpec) DeepCopy() *LLMBackendSpec {
	if in == nil {
		return nil
	}
	out := new(LLMBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMBackendStatus) DeepCopyInto(out *LLMBackendStatus) {
	*out = *in
	if in.ActiveModelSince != nil {
		in, out := &in.ActiveModelSince, &out.ActiveModelSince
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMBackendStatus.
func (in *LLMBackendStatus) DeepCopy() *LLMBackendStatus {
	if in == nil {
		return nil
	}
	out := new(LLMBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMModel) DeepCopyInto(out *LLMModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMModel.
func (in *LLMModel) DeepCopy() *LLMModel {
	if in == nil {
		return nil
	}
	out := new(LLMModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMModelList) DeepCopyInto(out *LLMModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LLMModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMModelList.
func (in *LLMModelList) DeepCopy() *LLMModelList {
	if in == nil {
		return nil
	}
	out := new(LLMModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMModelOverlay) DeepCopyInto(out *LLMModelOverlay) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMModelOverlay.
func (in *LLMModelOverlay) DeepCopy() *LLMModelOverlay {
	if in == nil {
		return nil
	}
	out := new(LLMModelOverlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMModelOverlay) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMModelOverlayList) DeepCopyInto(out *LLMModelOverlayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LLMModelOverlay, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMModelOverlayList.
func (in *LLMModelOverlayList) DeepCopy() *LLMModelOverlayList {
	if in == nil {
		return nil
	}
	out := new(LLMModelOverlayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMModelOverlayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMModelOverlaySpec) DeepCopyInto(out *LLMModelOverlaySpec) {
	*out = *in
	if in.RequestDefaults != nil {
		in, out := &in.RequestDefaults, &out.RequestDefaults
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMModelOverlaySpec.
func (in *LLMModelOverlaySpec) DeepCopy() *LLMModelOverlaySpec {
	if in == nil {
		return nil
	}
	out := new(LLMModelOverlaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMModelOverlayStatus) DeepCopyInto(out *LLMModelOverlayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMModelOverlayStatus.
func (in *LLMModelOverlayStatus) DeepCopy() *LLMModelOverlayStatus {
	if in == nil {
		return nil
	}
	out := new(LLMModelOverlayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMModelRef) DeepCopyInto(out *LLMModelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMModelRef.
func (in *LLMModelRef) DeepCopy() *LLMModelRef {
	if in == nil {
		return nil
	}
	out := new(LLMModelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMModelSpec) DeepCopyInto(out *LLMModelSpec) {
	*out = *in
	out.Model = in.Model
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(ArtifactSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Serving.DeepCopyInto(&out.Serving)
	if in.BackendRef != nil {
		in, out := &in.BackendRef, &out.BackendRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMModelSpec.
func (in *LLMModelSpec) DeepCopy() *LLMModelSpec {
	if in == nil {
		return nil
	}
	out := new(LLMModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMModelStatus) DeepCopyInto(out *LLMModelStatus) {
	*out = *in
	if in.CacheState != nil {
		in, out := &in.CacheState, &out.CacheState
		*out = new(CacheState)
		(*in).DeepCopyInto(*out)
	}
	if in.RuntimeMetadata != nil {
		in, out := &in.RuntimeMetadata, &out.RuntimeMetadata
		*out = new(RuntimeMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMModelStatus.
func (in *LLMModelStatus) DeepCopy() *LLMModelStatus {
	if in == nil {
		return nil
	}
	out := new(LLMModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeMetadata) DeepCopyInto(out *RuntimeMetadata) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.ServedModelIDs != nil {
		in, out := &in.ServedModelIDs, &out.ServedModelIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LaunchArguments != nil {
		in, out := &in.LaunchArguments, &out.LaunchArguments
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.KVCache != nil {
		in, out := &in.KVCache, &out.KVCache
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeMetadata.
func (in *RuntimeMetadata) DeepCopy() *RuntimeMetadata {
	if in == nil {
		return nil
	}
	out := new(RuntimeMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServingSpec) DeepCopyInto(out *ServingSpec) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServingSpec.
func (in *ServingSpec) DeepCopy() *ServingSpec {
	if in == nil {
		return nil
	}
	out := new(ServingSpec)
	in.DeepCopyInto(out)
	return out
}
